"""Updated migration

Revision ID: 461d92b007c1
Revises: 98e622e98e62
Create Date: 2025-07-15 22:30:47.879289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '461d92b007c1'
down_revision: Union[str, Sequence[str], None] = '98e622e98e62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('categories', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('product_variants', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('product_variants', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('products', 'base_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'base_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('product_variants', 'updated_at')
    op.drop_column('product_variants', 'created_at')
    op.drop_column('categories', 'updated_at')
    op.drop_column('categories', 'created_at')
    # ### end Alembic commands ###
