"""Initial migration

Revision ID: 98e622e98e62
Revises: 64820954bdbe
Create Date: 2025-07-15 16:50:53.972069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98e622e98e62'
down_revision: Union[str, Sequence[str], None] = '64820954bdbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('addresses', 'recipient_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('addresses', 'street_address1',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('addresses', 'city',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('addresses', 'state',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('addresses', 'postal_code',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('payments', 'method',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.alter_column('payments', 'method',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('addresses', 'postal_code',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('addresses', 'state',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('addresses', 'city',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('addresses', 'street_address1',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('addresses', 'recipient_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
